spring:
  application:
    name: email-sender

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${DB_DIALECT}

  redis:
    host: localhost
    port: 6379
    timeout: 60000

  mail:
    host: smtp.gmail.com
    port: 587
    username: foodconnecttech@gmail.com
    password: hvvt kian qmri nkxw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 5000
          timeout: 5000
          write timeout:

server:
  port: ${PORT:8080}