spring:
  application:
    name: email-sender
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
server:
  port: ${PORT:8080}