name: Deploy to Azure VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no FoodConnect@4.201.144.173 '
            set -e

            PROJECT_DIR="/home/FoodConnect/foodconnect-backend/email-sender"
            LOG_DIR="$HOME/logs"
            JAR_PATH="$PROJECT_DIR/target/email-sender-0.0.1-SNAPSHOT.jar"

            echo "Atualizando código fonte..."
            cd $PROJECT_DIR
            git pull origin main

            echo "Compilando aplicação..."
            ./mvnw clean package -DskipTests

            echo "Parando processo antigo da aplicação, se estiver rodando..."
            PID=$(pgrep -f "email-sender-0.0.1-SNAPSHOT.jar") || true
            if [ -n "$PID" ]; then
             kill "$PID"
             echo "Processo antigo parado com sucesso."
            else
              echo "Nenhum processo antigo encontrado."
            fi

            echo "Iniciando aplicação em segundo plano..."
            nohup java -jar $JAR_PATH > $LOG_DIR/email-sender.log 2>&1 &

            echo "Verificando se Redis está rodando..."
            docker ps | grep redis || {
              echo "Redis não está rodando. Subindo Redis..."
              docker compose -f /home/FoodConnect/docker-compose.yml up -d redis
            }

            echo "Deploy finalizado com sucesso!"
          '